name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: make build directory
      run: mkdir -p build
      
    - name: change to build directory
      run: cd build
      
    - name: cmake
      run: cmake -DCMAKE_OSX_ARCHITECTURES="x86_64"..
      
    - name: install
      run: make install
