name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: curl SDK
      run: curl -L0 https://cycling74.s3.amazonaws.com/download/max-sdk-8.0.3.zip --output sdk.zip

    - name: unzip
      run: unzip sdk.zip
      
    - name: make build directory
      run: mkdir -p build
      
    - name: cmake
      run: cmake -DMAX_SDK_PATH=../max-sdk-8.0.3/ ..
      working-directory: build
      
    - name: install
      run: make install
      working-directory: build
