name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: get SDK
      run: git clone https://github.com/Cycling74/max-sdk-base.git sdk

    - name: make build directory
      run: mkdir -p build
      
    - name: change to build directory
      run: cd build
      
    - name: cmake
      run: cmake -DMAX_SDK_PATH=../sdk/ -DCMAKE_OSX_ARCHITECTURES="x86_64"..
      
    - name: install
      run: make install
