name: C/C++ CI

on:
  push:
    branches: [ main, ci/automatic-building ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: install ninja
      run: brew install ninja

#     - name: curl SDK
#       run: curl -L0 https://cycling74.s3.amazonaws.com/download/max-sdk-8.0.3.zip --output sdk.zip

#     - name: unzip
#       run: unzip sdk.zip

    - name: get max sdk
      run: git clone --recursive https://github.com/Cycling74/max-sdk.git sdk
      
    - name: make build directory
      run: mkdir -p build
      
    - name: cmake
      run: cmake -GNinja -DMAX_SDK_PATH=../sdk/ ..
      working-directory: build
      
    - name: install
      run: ninja
      working-directory: build
